site_name: DungeonMice Backend
site_description: Documentación técnica del backend de DungeonMice
site_author: Physics in Silico
repo_url: https://github.com/DungeonMice/DungeonMice


nav:
- Inicio: index.md
- Primeros pasos: getting-started.md
- Arquitectura: architecture.md
- Módulos:
  - Labyrinths: 
    - Labyrinth: modules/labyrinths/labyrinth.md
    - Labyrinth_CrossMaze: modules/labyrinths/labyrinth_CrossMaze.md
    - Labyrinth_MorrisPool: modules/labyrinths/labyrinth_MorrisPool.md
  - Regions: modules/regions.md
  - Logic: modules/logic.md
  - Tracker: modules/tracker.md
  - input: modules/input.md
  - visualizer: modules/visualizer.md
  - experiment: modules/experiment.md
  - RunExperiment: modules/Run_Experiment.md
  - Run: modules/run.md
- Contribuir: contributions.md


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Modo oscuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro

markdown_extensions:
- admonition
- codehilite

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ['code/'] 
