site_name: DungeonMice Backend
site_description: Documentación técnica del backend de DungeonMice
site_author: Physics in Silico
repo_url: https://github.com/DungeonMice/DungeonMice


nav:
- Inicio: index.md
- Primeros pasos: getting-started.md
- Arquitectura: architecture.md
- Módulos:
  - prueba: modules/prueba.md
  - Labirynth: modules/labirynth.md
  - Regions: modules/regions.md
  - Logic: modules/logic.md
  - Tracker: modules/tracker.md
  - input: modules/input.md
  - visualizer: modules/visualizar.md
  - experiment: modules/experiment.md
- Contribuir: contributions.md


theme:
  name: material


markdown_extensions:
- admonition
- codehilite
- toc:
permalink: true
