site_name: DungeonMice Backend
site_description: Documentación técnica del backend de DungeonMice
site_author: Physics in Silico
repo_url: https://github.com/DungeonMice/DungeonMice


nav:
- Inicio: index.md
- Primeros pasos: getting-started.md
- Arquitectura: architecture.md
- Módulos:
  - prueba: docs/modules/prueba.md
  - Labirynth: docs/modules/labirynth.md
  - Regions: docs/modules/regions.md
  - Logic: docs/modules/logic.md
  - Tracker: docs/modules/tracker.md
  - input: docs/modules/input.md
  - visualizer: docs/modules/visualizar.md
  - experiment: docs/modules/experiment.md
- Contribuir: docs/contributions.md


theme:
  name: material


markdown_extensions:
- admonition
- codehilite

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../code]
